// Package skill holds the guide that tells an AI agent how to use mikado. It is
// embedded in the binary so the guide always matches the installed version.
package skill

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:embed SKILL.md
var text string

// marker is in every file `mikado skill install` writes, so a reinstall knows
// the file is its own to overwrite.
const marker = "generated by `mikado skill install`"

// Text returns the guide.
func Text() string { return text }

// DefaultDir is where Claude Code looks for a user-level skill named mikado.
func DefaultDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "skills", "mikado"), nil
}

// Install writes the guide to dir/SKILL.md and returns the file's path. It
// overwrites a file an earlier install wrote, and refuses any other file unless
// force is set.
func Install(dir string, force bool) (string, error) {
	path := filepath.Join(dir, "SKILL.md")
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if string(existing) == text {
			return path, nil
		}
		if !force && !strings.Contains(string(existing), marker) {
			return "", fmt.Errorf("%s exists and was not written by mikado; pass --force to replace it", path)
		}
	case !errors.Is(err, os.ErrNotExist):
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
